# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# Copyright (c) [2022] Nadege LEMPERIERE
# All rights reserved
# -------------------------------------------------------
# Latest pipeline for FLL mocks
# -------------------------------------------------------
# Nadège LEMPERIERE, @09 november 2022
# Latest revision: 09 november 2022
# -------------------------------------------------------

name: Fll Mocks Check Pipeline

on:
    push:
        branches:
            - '**'

jobs:

    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
          image: docker://nadegelemperiere/fll-test-docker:v1.2.0
          options: --user root
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              run: pip install -r requirements-test.txt --target site-packages

            - name: Installing dependencies
              run: pip install -r requirements.txt --target site-packages

            - name: Linting module
              continue-on-error: true
              run: pylint spike

            - name: Run pip-audit to check for vulnerabilities
              continue-on-error: true
              run: pip-audit -r requirements-test.txt --format json

            - name: Run pip-audit to check for vulnerabilities
              continue-on-error: true
              run: pip-audit -r requirements.txt --format json

    test:
        name: Testing Package
        runs-on: ubuntu-latest
        container:
          image: docker://nadegelemperiere/fll-test-docker:v1.2.0
          options: --user root
        needs: [check]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Launching tests
              continue-on-error: true
              run: ./scripts/robot.sh -l WARN -d tests
