# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# Copyright (c) [2022] Nadege LEMPERIERE
# All rights reserved
# -------------------------------------------------------
# Release pipeline for FLL mocks
# -------------------------------------------------------
# Nadège LEMPERIERE, @09 november 2022
# Latest revision: 09 november 2022
# -------------------------------------------------------

name: Fll Mocks Release Pipeline

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
          image: docker://nadegelemperiere/fll-test-docker:v1.2.0
          options: --user root
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              run: pip install -r requirements-test.txt --target site-packages

            - name: Linting module
              run: pylint spike

            - name: Run pip-audit to check for vulnerabilities
              run: pip-audit -r requirements-test.txt --format json

    test:
        name: Testing Package
        runs-on: ubuntu-latest
        container:
          image: docker://nadegelemperiere/fll-test-docker:v1.2.0
          options: --user root
        needs: [check]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Launching tests
              run: ./scripts/robot.sh -l WARN -d tests

            - name: Push test report to Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                publish_dir: ./tests
                github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                commit_message: "Generate Test report"
